name: Java CI
on:
  push:
    branches:
      - '[5-9]+.[0-9]+.x'
  pull_request:
    branches:
      - '[5-9]+.[0-9]+.x'

jobs:

  build_project:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        java: [11, 17]

    steps:

      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Run Gradle build
        uses: gradle/actions/setup-gradle@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        with:
          arguments: build

  publish_documentation:
    name: Publish Snapshot release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_project

    steps:

      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 11 }

      - name: Publish to Artifactory (repo.grails.org)
        uses: gradle/actions/setup-gradle@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          ORG_GRADLE_PROJECT_artifactoryPublishUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          ORG_GRADLE_PROJECT_artifactoryPublishPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
        with:
          arguments: |
            -Dorg.gradle.internal.publish.checksums.insecure=true
            publish

      - name: Generate Documentation
        if: success()
        uses: gradle/actions/setup-gradle@v3
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
        with:
          arguments: docs

      - name: Publish to Github Pages
        if: success()
        uses: micronaut-projects/github-pages-deploy-action@grails
        env:
          TARGET_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/docs
          DOC_FOLDER: gh-pages
          COMMIT_EMAIL: behlp@unityfoundation.io
          COMMIT_NAME: Puneet Behl